//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.16 at 04:19:38 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.chinatax.gov.cn/tirip/dataspec", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.pansky.integration.common.soa.xmlBean;
