//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.16 at 04:19:38 PM CST 
//


package com.pansky.integration.common.soa.xmlBean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tiripPackageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tiripPackageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identity" type="{http://www.chinatax.gov.cn/tirip/dataspec}identityType"/>
 *         &lt;element name="contentControl" type="{http://www.chinatax.gov.cn/tirip/dataspec}contentControlType" minOccurs="0"/>
 *         &lt;element name="routerSession" type="{http://www.chinatax.gov.cn/tirip/dataspec}routerSessionType" minOccurs="0"/>
 *         &lt;element name="businessContent" type="{http://www.chinatax.gov.cn/tirip/dataspec}businessContentType" minOccurs="0"/>
 *         &lt;element name="returnState" type="{http://www.chinatax.gov.cn/tirip/dataspec}returnStateType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="tiripPackage")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tiripPackageType", propOrder = {
    "identity",
    "contentControl",
    "routerSession",
    "businessContent",
    "returnState"
})
public class TiripPackageType {

    @XmlElement(required = true)
    protected IdentityType identity;
    protected ContentControlType contentControl;
    protected RouterSessionType routerSession;
    protected BusinessContentType businessContent;
    protected ReturnStateType returnState;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityType }
     *     
     */
    public IdentityType getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityType }
     *     
     */
    public void setIdentity(IdentityType value) {
        this.identity = value;
    }

    /**
     * Gets the value of the contentControl property.
     * 
     * @return
     *     possible object is
     *     {@link ContentControlType }
     *     
     */
    public ContentControlType getContentControl() {
        return contentControl;
    }

    /**
     * Sets the value of the contentControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentControlType }
     *     
     */
    public void setContentControl(ContentControlType value) {
        this.contentControl = value;
    }

    /**
     * Gets the value of the routerSession property.
     * 
     * @return
     *     possible object is
     *     {@link RouterSessionType }
     *     
     */
    public RouterSessionType getRouterSession() {
        return routerSession;
    }

    /**
     * Sets the value of the routerSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouterSessionType }
     *     
     */
    public void setRouterSession(RouterSessionType value) {
        this.routerSession = value;
    }

    /**
     * Gets the value of the businessContent property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessContentType }
     *     
     */
    public BusinessContentType getBusinessContent() {
        return businessContent;
    }

    /**
     * Sets the value of the businessContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessContentType }
     *     
     */
    public void setBusinessContent(BusinessContentType value) {
        this.businessContent = value;
    }

    /**
     * Gets the value of the returnState property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnStateType }
     *     
     */
    public ReturnStateType getReturnState() {
        return returnState;
    }

    /**
     * Sets the value of the returnState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnStateType }
     *     
     */
    public void setReturnState(ReturnStateType value) {
        this.returnState = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
