//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 09:46:56 AM CST 
//


package com.pansky.integration.common.soa.xmlBean.bussbusinessContent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 网上业务通用响应信息
 * 
 * <p>Java class for wsywTyRespBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wsywTyRespBody">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tyResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="returnInfo" type="{http://www.chinatax.gov.cn/dataspec/}returnInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wsywTyRespBody", propOrder = {
    "tyResult",
    "returnInfo"
})
public class WsywTyRespBody {

    protected String tyResult;
    protected ReturnInfo returnInfo;

    /**
     * Gets the value of the tyResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTyResult() {
        return tyResult;
    }

    /**
     * Sets the value of the tyResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTyResult(String value) {
        this.tyResult = value;
    }

    /**
     * Gets the value of the returnInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnInfo }
     *     
     */
    public ReturnInfo getReturnInfo() {
        return returnInfo;
    }

    /**
     * Sets the value of the returnInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnInfo }
     *     
     */
    public void setReturnInfo(ReturnInfo value) {
        this.returnInfo = value;
    }

}
