//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 09:46:55 AM CST 
//


package com.pansky.integration.common.soa.xmlBean.bussbusinessContent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 网上业务通用请求报文
 * 
 * <p>Java class for wsywTyRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wsywTyRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.chinatax.gov.cn/dataspec/}taxDoc">
 *       &lt;sequence>
 *         &lt;element name="wsywTyReqBody" type="{http://www.chinatax.gov.cn/dataspec/}wsywTyReqItem"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wsywTyRequest", propOrder = {
    "wsywTyReqBody"
})
@XmlRootElement
public class WsywTyRequest
    extends TaxDoc
{

    @XmlElement(required = true)
    protected WsywTyReqItem wsywTyReqBody;

    /**
     * Gets the value of the wsywTyReqBody property.
     * 
     * @return
     *     possible object is
     *     {@link WsywTyReqItem }
     *     
     */
    public WsywTyReqItem getWsywTyReqBody() {
        return wsywTyReqBody;
    }

    /**
     * Sets the value of the wsywTyReqBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsywTyReqItem }
     *     
     */
    public void setWsywTyReqBody(WsywTyReqItem value) {
        this.wsywTyReqBody = value;
    }

}
