//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.23 at 09:46:56 AM CST 
//


package com.pansky.integration.common.soa.xmlBean.bussbusinessContent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 网上业务通用响应报文
 * 
 * <p>Java class for wsywTyResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wsywTyResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.chinatax.gov.cn/dataspec/}taxDoc">
 *       &lt;sequence>
 *         &lt;element name="wsywTyResp" type="{http://www.chinatax.gov.cn/dataspec/}wsywTyRespBody"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wsywTyResponse", propOrder = {
    "wsywTyResp"
})
@XmlRootElement
public class WsywTyResponse
    extends TaxDoc
{

    @XmlElement(required = true)
    protected WsywTyRespBody wsywTyResp;

    /**
     * Gets the value of the wsywTyResp property.
     * 
     * @return
     *     possible object is
     *     {@link WsywTyRespBody }
     *     
     */
    public WsywTyRespBody getWsywTyResp() {
        return wsywTyResp;
    }

    /**
     * Sets the value of the wsywTyResp property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsywTyRespBody }
     *     
     */
    public void setWsywTyResp(WsywTyRespBody value) {
        this.wsywTyResp = value;
    }

}
